# Generated by Django 6.0.4 on 2026-04-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("experience", models.CharField(max_length=100)),
                (
                    "expected_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("address", models.TextField()),
                ("resume", models.FileField(upload_to="jobs/resumes/")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="jobs/photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.job",
                    ),
                ),
            ],
        ),
    ]
