# Generated by Django 5.2.12 on 2026-05-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='news_created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='create_date',
            new_name='news_updated_at',
        ),
    ]
