# Generated by Django 5.2.12 on 2026-05-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_created_at_news_news_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herobanner',
            old_name='created_at',
            new_name='herosection_created_at',
        ),
        migrations.AddField(
            model_name='herobanner',
            name='herosection_updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
