# Generated by Django 5.2.12 on 2026-05-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_created_at_herobanner_herosection_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='category_created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='category_updated_at',
        ),
    ]
