# Generated by Django 5.2.12 on 2026-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_created_at_category_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryservice',
            old_name='updated_at',
            new_name='Categoryservice_updated_at',
        ),
        migrations.RenameField(
            model_name='categoryservice',
            old_name='created_at',
            new_name='categoryservice_created_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='job_created_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='updated_at',
            new_name='job_updated_at',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='created_at',
            new_name='jobapplication_created_at',
        ),
        migrations.RenameField(
            model_name='servicescards',
            old_name='created_at',
            new_name='servicecard_created_at',
        ),
        migrations.RenameField(
            model_name='servicescards',
            old_name='updated_at',
            new_name='servicecard_updated_at',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobapplication_updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
