# Generated by Django 5.2.12 on 2026-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_updated_at_categoryservice_categoryservice_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='contact_created_at',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='created_at',
            new_name='footer_created_at',
        ),
        migrations.RenameField(
            model_name='servicefeedback',
            old_name='created_at',
            new_name='feedback_created_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicefeedback',
            name='feedback_updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
