# Generated by Django 6.0.6 on 2026-07-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_created_at_contact_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='cart_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/cart/'),
        ),
    ]
