# Generated by Django 6.0.6 on 2026-09-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_footer_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
