# Generated by Django 5.2.12 on 2026-05-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerremark_priority_customerremark_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='service_days',
            field=models.IntegerField(default=30),
        ),
    ]
