# Generated by Django 5.2.12 on 2026-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_payment_paid_amount_payment_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial_paid', 'Partial_Paid'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
