# Generated by Django 5.2.12 on 2026-05-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_booking_end_date_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
