# Generated by Django 5.2.12 on 2026-05-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_booking_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='renewal_requested',
            field=models.BooleanField(default=False),
        ),
    ]
