# Generated by Django 5.2.12 on 2026-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_booking_renewal_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_renewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='previous_total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='renewal_count',
            field=models.IntegerField(default=0),
        ),
    ]
