# Generated by Django 5.2.12 on 2026-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_booking_is_renewed_booking_previous_total_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor/license/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='vendor/pan/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
