# Generated by Django 5.2.12 on 2026-05-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='behaviour',
            field=models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='behaviour_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
