# Generated by Django 5.2.12 on 2026-05-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_behaviour_user_behaviour_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
