# Generated by Django 5.2.12 on 2026-05-14 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
