# Generated by Django 5.2.12 on 2026-05-20 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_termsacceptance_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
