# Generated by Django 5.2.12 on 2026-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_user_created_at_user_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
