# Generated by Django 5.2.12 on 2026-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_created_at_booking_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='payment_created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
