# Generated by Django 5.2.12 on 2026-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_created_at_payment_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='created_at',
            new_name='profile_created_at',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
