# Generated by Django 5.2.12 on 2026-05-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rename_created_at_vendorprofile_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsacceptance',
            options={'permissions': [('manage news', 'Can Manage News'), ('manage hero section', 'Can Manage Hero Section'), ('manage categories', 'Can Manage Categories'), ('manage categories service', 'Can Manage Categories Service'), ('manage service', 'Can Manage Service'), ('manage Job Application', 'Can Manage Job Application'), ('manage feedback', 'Can Manage Feedback'), ('manage inquery contact', 'Can Manage Inquery Contact'), ('manage footer', 'Can Manage Footer')]},
        ),
    ]
