# Generated by Django 5.2.12 on 2026-05-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_termsacceptance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsacceptance',
            options={'permissions': [('manage_news', 'Can Manage News'), ('manage_hero_section', 'Can Manage Hero Section'), ('manage_categories', 'Can Manage Categories'), ('manage_categories_service', 'Can Manage Categories Service'), ('manage_service', 'Can Manage Service'), ('manage_jobs', 'Can Manage Jobs'), ('manage_job_application', 'Can Manage Job Application'), ('manage_feedback', 'Can Manage Feedback'), ('manage_inquery_contact', 'Can Manage Inquery Contact'), ('manage_footer', 'Can Manage Footer')]},
        ),
    ]
