# Generated by Django 5.2.12 on 2026-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_termsacceptance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_amount',
            field=models.IntegerField(default=0),
        ),
    ]
