# Generated by Django 5.2.12 on 2026-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='page_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
