# Generated by Django 6.0.6 on 2026-07-01 08:01

from django.db import migrations

def move_booking_data_to_items(apps, schema_editor):
    Booking = apps.get_model('accounts', 'Booking')
    BookingItem = apps.get_model('accounts', 'BookingItem')
    
    for booking in Booking.objects.all():
        # Only migrate if service is set
        if booking.service:
            BookingItem.objects.create(
                booking=booking,
                service=booking.service,
                vendor=booking.vendor,
                status=booking.status,
                scheduled_date=booking.scheduled_date,
                scheduled_time=booking.scheduled_time,
                start_date=booking.start_date,
                end_date=booking.end_date,
                renewal_requested=booking.renewal_requested,
                is_renewed=booking.is_renewed,
                previous_total_days=booking.previous_total_days,
                renewal_count=booking.renewal_count,
            )

def reverse_booking_data(apps, schema_editor):
    Booking = apps.get_model('accounts', 'Booking')
    BookingItem = apps.get_model('accounts', 'BookingItem')
    
    for booking in Booking.objects.all():
        first_item = booking.items.first()
        if first_item:
            booking.service = first_item.service
            booking.vendor = first_item.vendor
            booking.status = first_item.status
            booking.scheduled_date = first_item.scheduled_date
            booking.scheduled_time = first_item.scheduled_time
            booking.start_date = first_item.start_date
            booking.end_date = first_item.end_date
            booking.renewal_requested = first_item.renewal_requested
            booking.is_renewed = first_item.is_renewed
            booking.previous_total_days = first_item.previous_total_days
            booking.renewal_count = first_item.renewal_count
            booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_booking_category_alter_booking_problem_and_more'),
    ]

    operations = [
        migrations.RunPython(move_booking_data_to_items, reverse_booking_data)
    ]
